#!/usr/bin/env sh
# End-to-end test of the Docker stack – the proof that installation, persistence,
# backup and restore really work:
#
#   1. fresh install from .env.example (secrets generated automatically)
#   2. all services healthy, setup via token from the log
#   3. create data (colony, feeding via sync, location, photo)
#   4. backup + full verification (test restore into temporary DB)
#   5. change/destroy data (delete colony, add colony, delete photo files)
#   6. restore → original state is back, photo byte-identical,
#      old sync cursors are invalidated (clients resync)
#   7. restart and rebuild the stack → data persists
#   8. retention keeps the right backups
#
# Runs in an isolated copy (own project name, port, network, data dir).
#   ./scripts/test-stack.sh [--keep]
# shellcheck disable=SC2010 # backup names are generated by us (dates), ls|grep is fine here
set -eu
SRC=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
KEEP=0; [ "${1:-}" = "--keep" ] && KEEP=1
PORT=${E2E_PORT:-18080}
PROJECT=acm-e2e
WORK=$(mktemp -d /tmp/acm-e2e.XXXXXX)
BASE="http://127.0.0.1:$PORT"

step() { printf '\n\033[1;36m▶ %s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✔ %s\033[0m\n' "$*"; }
fail() { printf '  \033[31m✘ %s\033[0m\n' "$*" >&2; cd "$WORK" && docker compose -p "$PROJECT" logs --tail 30 >&2 || true; exit 1; }

cleanup() {
  if [ "$KEEP" = 1 ]; then echo "kept: $WORK (docker compose -p $PROJECT …)"; return; fi
  cd "$WORK" 2>/dev/null && docker compose -p "$PROJECT" --profile proxy down -v --remove-orphans >/dev/null 2>&1 || true
  rm -rf "$WORK"
}
trap cleanup EXIT

api() { # method path [json] → body; sets $STATUS
  out=$(curl -s -w '\n%{http_code}' -X "$1" "$BASE$2" -H "Authorization: Bearer ${TOKEN:-}" \
        -H 'Content-Type: application/json' ${3:+--data "$3"})
  printf '%s\n' "$out" | tail -1 > "$WORK/.status"   # survives the $(…) subshell
  printf '%s\n' "$out" | sed '$d'                     # printf: dash's echo would mangle backslashes
}
expect() { st=$(cat "$WORK/.status"); [ "$st" = "$1" ] || fail "expected HTTP $1, got $st ($2)"; }

step "Isolierte Kopie vorbereiten ($WORK)"
tar -C "$SRC" --exclude=./.git --exclude=./data -cf - . | tar -C "$WORK" -xf -
cd "$WORK"
cp .env.example .env
sed -i "s#^PUBLIC_APP_URL=.*#PUBLIC_APP_URL=$BASE#; s#^APP_PORT=.*#APP_PORT=$PORT#; s#^APP_BIND=.*#APP_BIND=127.0.0.1#;
        s#^ACM_SUBNET=.*#ACM_SUBNET=172.30.199.0/24#; s#^BACKUP_KEEP_DAILY=.*#BACKUP_KEEP_DAILY=3#;
        s#^ACM_VERSION=.*#ACM_VERSION=e2e#" .env
export COMPOSE_PROJECT_NAME=$PROJECT
dc() { docker compose -p "$PROJECT" "$@"; }
ok ".env aus .env.example – ohne Secrets"

step "1. Installation: docker compose up -d --build"
dc up -d --build --quiet-pull 2>&1 | tail -3
for s in db app backup; do
  i=0
  until [ "$(docker inspect -f '{{.State.Health.Status}}' "$(dc ps -q $s)")" = healthy ]; do
    i=$((i+2)); [ $i -gt 240 ] && fail "$s not healthy"; sleep 2
  done
  ok "$s healthy"
done
[ -s data/secrets/jwt_secret ] && [ -s data/secrets/postgres_password ] || fail "secrets not generated"
ok "Secrets automatisch erzeugt ($(ls data/secrets | tr '\n' ' '))"
[ "$(stat -c %a data/secrets/jwt_secret)" = 440 ] || fail "secret permissions"
dc logs app | grep -q '"password"\|JWT_SECRET=' && fail "secrets in logs" || ok "keine Secrets in den Logs"

step "2. Ersteinrichtung mit Setup-Code aus dem Log"
SETUP=$(dc logs app | grep -A1 'Setup-Code' | tail -1 | tr -d ' │|' | sed 's/.*app-1//')
[ -n "$SETUP" ] || fail "no setup token in log"
TOKEN=$(api POST /api/v1/setup "{\"email\":\"admin@ants.test\",\"password\":\"Formicarium-2026!\",\"setup_token\":\"$SETUP\"}" | jq -r .access_token)
expect 201 setup
ok "Admin angelegt"

step "3. Daten anlegen"
LOC=$(api POST /api/v1/locations '{"name":"Regal A"}' | jq -r .data.id); expect 201 location
COL=$(api POST /api/v1/colonies "{\"name\":\"Messor #12\",\"species_text\":\"Messor barbarus\",\"location_id\":\"$LOC\"}" | jq -r .data.id)
expect 201 colony
EV=$(cat /proc/sys/kernel/random/uuid)
PUSH=$(api POST /api/v1/sync/push "{\"device_id\":\"$(cat /proc/sys/kernel/random/uuid)\",\"ops\":[{\"op_id\":\"$(cat /proc/sys/kernel/random/uuid)\",\"entity\":\"colony_events\",\"entity_id\":\"$EV\",\"op\":\"create\",\"payload\":{\"colony_id\":\"$COL\",\"type\":\"feeding\",\"feeding\":{\"items\":[{\"food_name\":\"Schabe\",\"category\":\"protein\",\"quantity\":2}]}}}]}")
[ "$(printf '%s' "$PUSH" | jq -r '.results[0].status')" = applied ] || fail "sync push: $PUSH"
PH=$(cat /proc/sys/kernel/random/uuid)
api POST /api/v1/photos "{\"id\":\"$PH\",\"colony_id\":\"$COL\"}" >/dev/null; expect 201 photo
curl -sf -X PUT "$BASE/api/v1/photos/$PH/content" -H "Authorization: Bearer $TOKEN" --data-binary @scripts/testdata/ant.jpg >/dev/null || fail "upload"
URL=$(api GET "/api/v1/photos/$PH/url" | jq -r .url)
curl -sf "$BASE$URL" -o "$WORK/photo-before.jpg" || fail "download"
CURSOR=$(api GET "/api/v1/sync/pull?since=0" | jq -r .next)
ok "Kolonie, Standort, Fütterung (Sync), Foto angelegt – Cursor $CURSOR"

step "4. Backup + vollständige Prüfung"
./scripts/backup.sh --tag e2e | tail -2
NAME=$(ls data/backups | grep -- '-e2e$' | head -1)
[ -f "data/backups/$NAME/OK" ] || fail "backup missing"
[ "$(jq -r .counts.colonies data/backups/$NAME/manifest.json)" = 1 ] || fail "manifest counts"
./scripts/verify-backup.sh "$NAME" | tail -1
ok "Backup $NAME erstellt und durch Test-Restore verifiziert"
./scripts/backup.sh >/dev/null
SECOND=$(ls data/backups | grep -E '^[0-9-]+T[0-9]+$' | tail -1)
a=$(find "data/backups/$NAME/uploads" -type f -name '*.jpg' | head -1)
b="data/backups/$SECOND/uploads/${a#data/backups/$NAME/uploads/}"
[ "$(stat -c %i "$a")" = "$(stat -c %i "$b")" ] || fail "second backup should hard-link unchanged photos"
ok "Zweites Backup verlinkt unveränderte Fotos (inkrementell)"

step "5. Daten verändern / zerstören"
api DELETE "/api/v1/colonies/$COL" >/dev/null; expect 204 delete
api POST /api/v1/colonies '{"name":"Nach dem Backup","species_text":"Lasius niger"}' >/dev/null; expect 201 colony2
find data/uploads -type f -delete
ok "Kolonie gelöscht, neue Kolonie angelegt, alle Fotodateien gelöscht"

step "6. Restore"
./scripts/restore.sh "$NAME" --yes | tail -3
TOKEN=$(api POST /api/v1/auth/login '{"email":"admin@ants.test","password":"Formicarium-2026!"}' | jq -r .access_token)
expect 200 login
api GET "/api/v1/colonies/$COL" >/dev/null; expect 200 "restored colony"
[ "$(api GET /api/v1/colonies | jq -r .count)" = 1 ] || fail "colony created after the backup must be gone"
[ "$(api GET "/api/v1/colonies/$COL/timeline" | jq -r '.events | length')" = 1 ] || fail "feeding missing"
URL=$(api GET "/api/v1/photos/$PH/url" | jq -r .url)
curl -sf "$BASE$URL" -o "$WORK/photo-after.jpg" || fail "photo download after restore"
cmp -s "$WORK/photo-before.jpg" "$WORK/photo-after.jpg" || fail "photo differs after restore"
api GET "/api/v1/sync/pull?since=$CURSOR" >/dev/null; expect 410 "old cursor must require resync"
ls data/backups | grep -q -- '-pre-restore$' || fail "no safety backup before restore"
ok "Kolonie, Fütterung und Foto (bytegleich) wiederhergestellt; Apps werden zum Neuladen gezwungen; Sicherheits-Backup vorhanden"

step "7. Neustart und Neubau erhalten die Daten"
dc down >/dev/null 2>&1
dc up -d --build --quiet-pull >/dev/null 2>&1
i=0; until [ "$(docker inspect -f '{{.State.Health.Status}}' "$(dc ps -q app)" 2>/dev/null)" = healthy ]; do i=$((i+2)); [ $i -gt 180 ] && fail "app after restart"; sleep 2; done
TOKEN=$(api POST /api/v1/auth/login '{"email":"admin@ants.test","password":"Formicarium-2026!"}' | jq -r .access_token)
api GET "/api/v1/colonies/$COL" >/dev/null; expect 200 "colony after restart"
ok "Daten nach down/up --build vorhanden"

step "8. Aufbewahrung (GFS)"
dc exec -T backup sh -c '
  cd /data/backups
  src=$(ls | grep -E "^[0-9-]+T[0-9]+$" | tail -1)
  for i in $(seq 1 60); do
    d=$(date -d "-$i day" +%Y-%m-%d)T0300
    mkdir "$d" && cp "$src/manifest.json" "$d/" && touch "$d/OK"
  done
  /app/backup.sh prune >/dev/null
  auto=$(ls | grep -cE "^[0-9-]+T[0-9]+$")
  newest=$(ls | grep -E "^[0-9-]+T0300$" | sort -r | head -2 | tr "\n" " ")
  echo "$auto $newest"
  ls | grep -q -- "-e2e$" && ls | grep -q -- "-pre-restore$" && echo tagged-kept' > "$WORK/prune.txt"
cat "$WORK/prune.txt"
n=$(head -1 "$WORK/prune.txt" | cut -d' ' -f1)
[ "$n" -ge 5 ] && [ "$n" -le 10 ] || fail "unexpected number of kept backups: $n"
grep -q tagged-kept "$WORK/prune.txt" || fail "tagged backups must survive retention"
ok "Retention behält $n automatische Backups (3 täglich + wöchentlich + monatlich), benannte bleiben"

step "9. HTTPS-Proxy (Caddy, interne CA) inkl. Realtime-Stream"
sed -i "s#^COMPOSE_PROFILES=.*#COMPOSE_PROFILES=proxy#; s#^ACM_DOMAIN=.*#ACM_DOMAIN=ants.home.arpa#;
        s#^ACM_TLS_MODE=.*#ACM_TLS_MODE=internal#; s#^HTTP_PORT=.*#HTTP_PORT=18081#; s#^HTTPS_PORT=.*#HTTPS_PORT=18443#;
        s#^TRUSTED_PROXIES=.*#TRUSTED_PROXIES=172.30.199.0/24#" .env
dc up -d >/dev/null 2>&1
i=0; until [ "$(docker inspect -f '{{.State.Health.Status}}' "$(dc ps -q proxy)" 2>/dev/null)" = healthy ]; do i=$((i+2)); [ $i -gt 120 ] && fail "proxy"; sleep 2; done
P="https://ants.home.arpa:18443"
R="--resolve ants.home.arpa:18443:127.0.0.1 -k"
i=0; until curl -sf $R "$P/readyz" >/dev/null; do i=$((i+1)); [ $i -gt 30 ] && fail "https via caddy"; sleep 1; done
curl -sI $R "$P/readyz" | grep -qi '^strict-transport-security' || true
curl -s $R -o /dev/null -w '%{http_version}' "$P/healthz" | grep -q 2 || fail "expected HTTP/2 via caddy"
ok "HTTPS über Caddy (HTTP/2, interne CA) erreichbar"
( curl -sN $R --max-time 8 -H "Authorization: Bearer $TOKEN" "$P/api/v1/sync/events" > "$WORK/sse.txt" ) &
sleep 2
api POST /api/v1/locations '{"name":"SSE-Test"}' >/dev/null
wait || true
grep -q '^event: change' "$WORK/sse.txt" || fail "SSE event not delivered through proxy: $(cat "$WORK/sse.txt")"
ok "Realtime-Signal (SSE) kommt ungepuffert durch den Proxy"

step "Status"
dc ps --format 'table {{.Service}}\t{{.Status}}'
printf '\n\033[1;32mAlle E2E-Prüfungen bestanden.\033[0m\n'
