-- Artenkatalog mit Steckbrief: Herkunft, Größen, Klima, Winterruhe, Kolonie,
-- Gründung, Futter und Haltung. Kolonien verweisen per species_id auf eine Art
-- und zeigen deren Steckbrief. Alle Werte sind Richtwerte für die Haltung.
ALTER TABLE species
    ADD COLUMN tribe                text,
    ADD COLUMN distribution         text,
    ADD COLUMN habitat              text,
    ADD COLUMN queen_size           text,
    ADD COLUMN worker_size          text,
    ADD COLUMN male_size            text,
    ADD COLUMN coloration           text,
    ADD COLUMN polymorphic          boolean,
    ADD COLUMN temp_arena_min       numeric(4,1),
    ADD COLUMN temp_arena_max       numeric(4,1),
    ADD COLUMN temp_nest_min        numeric(4,1),
    ADD COLUMN temp_nest_max        numeric(4,1),
    ADD COLUMN humidity_arena_min   smallint CHECK (humidity_arena_min BETWEEN 0 AND 100),
    ADD COLUMN humidity_arena_max   smallint CHECK (humidity_arena_max BETWEEN 0 AND 100),
    ADD COLUMN humidity_nest_min    smallint CHECK (humidity_nest_min BETWEEN 0 AND 100),
    ADD COLUMN humidity_nest_max    smallint CHECK (humidity_nest_max BETWEEN 0 AND 100),
    ADD COLUMN hibernation          text CHECK (hibernation IN ('none', 'optional', 'required')),
    ADD COLUMN hibernation_period   text,
    ADD COLUMN hibernation_temp_min numeric(4,1),
    ADD COLUMN hibernation_temp_max numeric(4,1),
    ADD COLUMN gyne_type            text CHECK (gyne_type IN ('monogyne', 'oligogyne', 'polygyne', 'facultative')),
    ADD COLUMN founding             text CHECK (founding IN ('claustral', 'semi_claustral', 'parasitic', 'dependent')),
    ADD COLUMN colony_size          text,
    ADD COLUMN queen_lifespan       text,
    ADD COLUMN development          text,
    ADD COLUMN nuptial_flight       text,
    ADD COLUMN difficulty           smallint CHECK (difficulty BETWEEN 1 AND 3),
    ADD COLUMN activity             text CHECK (activity IN ('diurnal', 'nocturnal', 'both')),
    ADD COLUMN diet_protein         text,
    ADD COLUMN diet_carbohydrate    text,
    ADD COLUMN diet_notes           text,
    ADD COLUMN nesting              text,
    ADD COLUMN formicarium          text,
    ADD COLUMN formicarium_size     text,
    ADD COLUMN substrate            text,
    ADD COLUMN legal_note           text,
    ADD COLUMN sources              jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(sources) = 'array'),
    ADD CONSTRAINT species_temp_arena CHECK (temp_arena_min IS NULL OR temp_arena_max IS NULL OR temp_arena_min <= temp_arena_max),
    ADD CONSTRAINT species_temp_nest  CHECK (temp_nest_min IS NULL OR temp_nest_max IS NULL OR temp_nest_min <= temp_nest_max),
    ADD CONSTRAINT species_hum_arena  CHECK (humidity_arena_min IS NULL OR humidity_arena_max IS NULL OR humidity_arena_min <= humidity_arena_max),
    ADD CONSTRAINT species_hum_nest   CHECK (humidity_nest_min IS NULL OR humidity_nest_max IS NULL OR humidity_nest_min <= humidity_nest_max),
    ADD CONSTRAINT species_temp_winter CHECK (hibernation_temp_min IS NULL OR hibernation_temp_max IS NULL
                                              OR hibernation_temp_min <= hibernation_temp_max);

CREATE INDEX species_german_trgm ON species USING gin (german_name gin_trgm_ops);

-- Körnersammler (Messor, Pheidole) leben vor allem von Samen.
INSERT INTO food_items (owner_id, name, category, default_unit, sort_order) VALUES
    (NULL, 'Samen', 'protein', 'portion', 85)
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- Startkatalog. Taxonomie nach AntCat/AntWiki; Haltungswerte sind Richtwerte
-- aus Fachliteratur und Haltungspraxis und werden in der App so gekennzeichnet.
-- -----------------------------------------------------------------------------
CREATE FUNCTION pg_temp.antwiki(name text) RETURNS jsonb LANGUAGE sql AS $$
    SELECT jsonb_build_array(jsonb_build_object('title', 'AntWiki', 'url', 'https://www.antwiki.org/wiki/' || replace(name, ' ', '_')))
$$;
CREATE FUNCTION pg_temp.seifert() RETURNS jsonb LANGUAGE sql AS $$
    SELECT '[{"title": "Seifert, B. (2018): The Ants of Central and North Europe. lutra Verlag"}]'::jsonb
$$;

INSERT INTO species (owner_id, scientific_name, genus, subfamily, tribe, german_name, distribution, habitat,
    queen_size, worker_size, male_size, coloration, polymorphic,
    temp_arena_min, temp_arena_max, temp_nest_min, temp_nest_max,
    humidity_arena_min, humidity_arena_max, humidity_nest_min, humidity_nest_max,
    hibernation, hibernation_period, hibernation_temp_min, hibernation_temp_max,
    gyne_type, founding, colony_size, queen_lifespan, development, nuptial_flight,
    difficulty, activity, diet_protein, diet_carbohydrate, diet_notes,
    nesting, formicarium, formicarium_size, substrate, legal_note, notes, sources) VALUES
-- Mitteleuropa
(NULL, 'Lasius niger', 'Lasius', 'Formicinae', 'Lasiini', 'Schwarzgraue Wegameise',
    'Europa, West- und Zentralasien', 'Offenes Gelände, Gärten, Wegränder, Siedlungen',
    '8–9 mm', '3–5 mm', '3,5–4,5 mm', 'Schwarzbraun bis grauschwarz', false,
    18, 28, 20, 25, 40, 60, 50, 70,
    'required', 'Oktober – März', 5, 8,
    'monogyne', 'claustral', 'bis über 10.000 Arbeiterinnen', 'bis ca. 29 Jahre (Rekord in Haltung)', 'ca. 6–8 Wochen vom Ei zur Arbeiterin', 'Juni – August',
    1, 'both', 'Kleine Insekten: Fruchtfliegen, Heimchen, Grillen, Schaben (Stücke)', 'Honigwasser, Zuckerwasser; in der Natur vor allem Honigtau von Blattläusen', NULL,
    'Erdnester, gern unter Steinen; auch in morschem Holz', 'Ytong, Gips, Acryl, Erdnest', 'S–M', 'Sand-Lehm-Gemisch',
    NULL, 'Robuste Einsteigerart. Gründungsköniginnen brauchen bis zu den ersten Arbeiterinnen kein Futter.',
    pg_temp.antwiki('Lasius niger') || pg_temp.seifert()),
(NULL, 'Lasius flavus', 'Lasius', 'Formicinae', 'Lasiini', 'Gelbe Wiesenameise',
    'Europa, Asien, Nordafrika', 'Wiesen und Weiden, baut Erdhügel',
    '7–9 mm', '2–4,5 mm', '3–4 mm', 'Gelb bis gelbbraun; Königin braun', false,
    18, 25, 20, 24, 50, 70, 60, 80,
    'required', 'Oktober – März', 5, 8,
    'monogyne', 'claustral', 'bis mehrere 10.000 Arbeiterinnen', 'über 15 Jahre', 'langsam, oft 2–3 Monate', 'Juli – August',
    2, 'both', 'Kleine Insekten, zerteilt', 'Honigwasser; lebt in der Natur fast nur von Honigtau unterirdischer Wurzelläuse', NULL,
    'Rein unterirdisch, kommt kaum an die Oberfläche', 'Erdnest, Ytong mit Erde, feuchtes Gipsnest', 'S–M', 'Erde, Sand-Lehm-Gemisch',
    NULL, 'Wächst langsam und zeigt sich selten – eher für geduldige Halter.',
    pg_temp.antwiki('Lasius flavus') || pg_temp.seifert()),
(NULL, 'Formica fusca', 'Formica', 'Formicinae', 'Formicini', 'Grauschwarze Sklavenameise',
    'Europa, gemäßigtes Asien', 'Waldränder, Lichtungen, Gärten',
    '10–11 mm', '4,5–7 mm', '9–11 mm', 'Grauschwarz, seidig schimmernd', false,
    18, 28, 20, 26, 40, 60, 50, 70,
    'required', 'Oktober – März', 5, 8,
    'facultative', 'claustral', 'einige hundert bis 2.000 Arbeiterinnen', 'bis ca. 20 Jahre', 'ca. 6–8 Wochen', 'Juni – August',
    1, 'diurnal', 'Insekten, relativ hoher Proteinbedarf während der Brutaufzucht', 'Honigwasser, Zuckerwasser, Früchte', NULL,
    'Erdnester, unter Steinen, in Baumstümpfen', 'Ytong, Gips, Acryl, Erdnest', 'M', 'Sand-Lehm-Gemisch',
    'Nicht zu verwechseln mit den geschützten hügelbauenden Waldameisen (Formica-rufa-Gruppe).',
    'Schnelle, scheue Art – Ausbruchschutz wichtig.',
    pg_temp.antwiki('Formica fusca') || pg_temp.seifert()),
(NULL, 'Formica rufibarbis', 'Formica', 'Formicinae', 'Formicini', 'Rotbärtige Sklavenameise',
    'Europa, Zentralasien', 'Trockene, warme Offenflächen, Magerrasen',
    '10–11 mm', '4,5–7 mm', '9–10 mm', 'Kopf und Hinterleib schwarz, Brustabschnitt rötlich', false,
    18, 30, 20, 26, 30, 50, 50, 70,
    'required', 'Oktober – März', 5, 8,
    'monogyne', 'claustral', 'einige hundert bis wenige tausend Arbeiterinnen', 'über 10 Jahre', 'ca. 6–8 Wochen', 'Juni – Juli',
    1, 'diurnal', 'Insekten', 'Honigwasser, Zuckerwasser, Früchte', NULL,
    'Erdnester in trockenen, sonnigen Böden', 'Ytong, Gips, Acryl, Erdnest', 'M', 'Sand, Sand-Lehm-Gemisch',
    'Nicht zu verwechseln mit den geschützten hügelbauenden Waldameisen (Formica-rufa-Gruppe).',
    'Wärmeliebend, sehr flink – Ausbruchschutz wichtig.',
    pg_temp.antwiki('Formica rufibarbis') || pg_temp.seifert()),
(NULL, 'Formica sanguinea', 'Formica', 'Formicinae', 'Formicini', 'Blutrote Raubameise',
    'Europa, gemäßigtes Asien', 'Waldränder, Heiden, Lichtungen',
    '9–11 mm', '6–8 mm', '9–11 mm', 'Kopf und Brustabschnitt rot, Hinterleib schwarz', false,
    18, 28, 20, 26, 40, 60, 50, 70,
    'required', 'Oktober – März', 5, 8,
    'facultative', 'parasitic', 'einige tausend Arbeiterinnen', 'über 10 Jahre', 'ca. 6–8 Wochen', 'Juli – August',
    3, 'diurnal', 'Insekten, Puppen von Serviformica (Raubzüge)', 'Honigwasser, Zuckerwasser', NULL,
    'Erdnester, oft mit Hilfsameisen (Formica fusca, F. rufibarbis)', 'Erdnest, Ytong', 'M–L', 'Sand-Lehm-Gemisch',
    NULL, 'Sozialparasit: Die Königin gründet nur mit Puppen oder Arbeiterinnen einer Hilfsart. Für Fortgeschrittene.',
    pg_temp.antwiki('Formica sanguinea') || pg_temp.seifert()),
(NULL, 'Camponotus ligniperda', 'Camponotus', 'Formicinae', 'Camponotini', 'Braunschwarze Rossameise',
    'Mittel- und Südeuropa bis Westasien', 'Lichte, warme Wälder, Waldränder',
    '14–18 mm', '7–14 mm', '9–12 mm', 'Schwarz mit rotbraunem Brustabschnitt und Hinterleibsbasis', true,
    18, 28, 20, 25, 40, 60, 50, 70,
    'required', 'Oktober – März', 5, 10,
    'monogyne', 'claustral', 'bis wenige tausend Arbeiterinnen', 'über 20 Jahre', 'ca. 8 Wochen; langsame Entwicklung im ersten Jahr', 'Mai – Juni',
    1, 'diurnal', 'Insekten: Heimchen, Grillen, Schaben, Fliegen', 'Honigwasser, Zuckerwasser, süße Früchte', NULL,
    'In morschem Holz und im Boden unter Steinen', 'Ytong, Gips, Holz, Acryl', 'M–L', 'Sand-Lehm-Gemisch',
    NULL, 'Die erste Winterruhe ist wichtig, danach wächst die Kolonie deutlich schneller.',
    pg_temp.antwiki('Camponotus ligniperda') || pg_temp.seifert()),
(NULL, 'Camponotus herculeanus', 'Camponotus', 'Formicinae', 'Camponotini', 'Riesenholzameise',
    'Nord- und Mitteleuropa, Nordasien, Nordamerika', 'Nadelwälder, im Gebirge bis zur Baumgrenze',
    '14–18 mm', '6–14 mm', '9–12 mm', 'Schwarz mit rotbraunem Brustabschnitt', true,
    18, 26, 18, 24, 40, 60, 50, 70,
    'required', 'Oktober – April', 3, 8,
    'monogyne', 'claustral', 'bis mehrere tausend Arbeiterinnen', 'über 20 Jahre', 'ca. 8–10 Wochen', 'Mai – Juli',
    2, 'nocturnal', 'Insekten', 'Honigwasser, Zuckerwasser', NULL,
    'In Stämmen und Stümpfen von Nadelbäumen', 'Holz, Ytong, Gips', 'M–L', 'Sand-Lehm-Gemisch, Rindenstücke',
    NULL, 'Braucht eine lange, kühle Winterruhe.',
    pg_temp.antwiki('Camponotus herculeanus') || pg_temp.seifert()),
(NULL, 'Messor structor', 'Messor', 'Myrmicinae', 'Stenammini', 'Ernteameise',
    'Süd- und Mitteleuropa (in Österreich v. a. im Osten), bis Zentralasien', 'Trockene, warme Offenflächen, Trockenrasen',
    '9–11 mm', '3,5–10 mm', '8–9 mm', 'Dunkelbraun bis schwarz', true,
    20, 30, 22, 26, 30, 50, 40, 60,
    'required', 'November – März', 5, 10,
    'monogyne', 'claustral', 'mehrere tausend Arbeiterinnen', 'über 10 Jahre', 'ca. 6–8 Wochen', 'Mai – Juli',
    1, 'diurnal', 'Samen (Grassamen, Löwenzahn, Chia, Mohn); zusätzlich Insekten', 'Kaum nötig; gelegentlich Honigwasser', 'Samen trocken anbieten, verschimmelte Kammern räumt die Kolonie selbst aus.',
    'Tiefe Erdnester mit Samenkammern', 'Ytong, Gips, Erdnest; trockene Kammern für den Samenvorrat', 'M–L', 'Sand, Sand-Lehm-Gemisch',
    NULL, 'Körnersammler – ideal für Einsteiger mit wenig Zeit.',
    pg_temp.antwiki('Messor structor') || pg_temp.seifert()),
(NULL, 'Tetramorium caespitum', 'Tetramorium', 'Myrmicinae', 'Crematogastrini', 'Rasenameise',
    'Europa, gemäßigtes Asien; eingeschleppt in Nordamerika', 'Offene, sonnige Flächen, Wegränder, Rasen',
    '6–8 mm', '2,5–4 mm', '5–7 mm', 'Dunkelbraun bis schwarz', false,
    18, 30, 20, 26, 40, 60, 50, 70,
    'required', 'Oktober – März', 5, 8,
    'monogyne', 'claustral', 'bis mehrere 10.000 Arbeiterinnen', 'über 10 Jahre', 'ca. 6–8 Wochen', 'Juni – Juli',
    1, 'diurnal', 'Insekten, auch Samen', 'Honigwasser, Zuckerwasser', NULL,
    'Erdnester unter Steinen und in Pflasterritzen', 'Ytong, Gips, Acryl', 'M', 'Sand-Lehm-Gemisch',
    NULL, 'Eigentlich ein Artkomplex, im Feld kaum unterscheidbar. Aktiv, kann stechen, aber schwach.',
    pg_temp.antwiki('Tetramorium caespitum') || pg_temp.seifert()),
(NULL, 'Myrmica rubra', 'Myrmica', 'Myrmicinae', 'Myrmicini', 'Rotgelbe Knotenameise',
    'Europa, gemäßigtes Asien; eingeschleppt in Nordamerika', 'Feuchte Wiesen, Gärten, Waldränder',
    '5,5–7 mm', '4–5,5 mm', '5–6 mm', 'Rotbraun bis gelbrot', false,
    18, 25, 20, 24, 50, 70, 60, 80,
    'required', 'Oktober – März', 5, 8,
    'polygyne', 'semi_claustral', 'einige hundert bis wenige tausend Arbeiterinnen', 'über 10 Jahre', 'ca. 6–8 Wochen', 'August – September',
    1, 'both', 'Insekten', 'Honigwasser, Zuckerwasser', 'Gründungsköniginnen gehen auf Futtersuche und brauchen Futter.',
    'Erdnester, unter Steinen, in Moos und Totholz', 'Ytong, Gips, Acryl', 'S–M', 'Erde, Sand-Lehm-Gemisch',
    NULL, 'Mag es feucht. Sticht spürbar.',
    pg_temp.antwiki('Myrmica rubra') || pg_temp.seifert()),
(NULL, 'Manica rubida', 'Manica', 'Myrmicinae', 'Myrmicini', NULL,
    'Gebirge Süd- und Mitteleuropas, u. a. Alpen', 'Sonnige, steinige Hänge und Schotterflächen im Bergland',
    '9–11 mm', '5–7,5 mm', '7–9 mm', 'Rotbraun', false,
    18, 26, 18, 24, 40, 60, 50, 70,
    'required', 'Oktober – April', 3, 8,
    'facultative', 'semi_claustral', 'einige hundert bis wenige tausend Arbeiterinnen', 'über 10 Jahre', 'ca. 6–8 Wochen', 'Juni – August',
    2, 'diurnal', 'Insekten', 'Honigwasser, Zuckerwasser', 'Gründungsköniginnen brauchen Futter.',
    'Erdnester unter Steinen', 'Ytong, Gips', 'M', 'Sand-Lehm-Gemisch, Kies',
    NULL, 'Sticht schmerzhaft. Lange Winterruhe nötig.',
    pg_temp.antwiki('Manica rubida') || pg_temp.seifert()),
(NULL, 'Temnothorax nylanderi', 'Temnothorax', 'Myrmicinae', 'Crematogastrini', NULL,
    'West- und Mitteleuropa', 'Laubwälder, in Eicheln, Nussschalen und Ästchen',
    '3,5–4 mm', '2–3 mm', '3 mm', 'Gelbbraun, Hinterleib mit dunklem Band', false,
    18, 25, 20, 24, 50, 70, 60, 80,
    'required', 'Oktober – März', 5, 8,
    'facultative', 'claustral', 'meist unter 200 Arbeiterinnen', 'über 10 Jahre', 'ca. 6–8 Wochen', 'Juli – August',
    1, 'both', 'Kleine Insekten (Fruchtfliegen, zerteilte Heimchen)', 'Honigwasser, Zuckerwasser', 'Futter nur in kleinen Mengen, Reste schnell entfernen.',
    'In Hohlräumen von Eicheln, Nüssen und dünnen Ästen', 'Reagenzglas, kleine Acryl- oder Gipsnester', 'S', 'Waldboden, Laub',
    NULL, 'Winzige, sehr platzsparende Art.',
    pg_temp.antwiki('Temnothorax nylanderi') || pg_temp.seifert()),
-- Mittelmeerraum
(NULL, 'Messor barbarus', 'Messor', 'Myrmicinae', 'Stenammini', 'Ernteameise',
    'Westliches Mittelmeergebiet: Iberische Halbinsel, Südfrankreich, Italien, Nordafrika', 'Trockene, offene Flächen, Felder',
    '12–15 mm', '3–13 mm', '9–10 mm', 'Schwarz; große Arbeiterinnen mit rotem Kopf', true,
    20, 30, 22, 28, 30, 50, 40, 60,
    'optional', 'November – Februar (kühlere Ruhephase)', 12, 18,
    'monogyne', 'claustral', 'bis mehrere 10.000 Arbeiterinnen', 'über 10 Jahre', 'ca. 6–8 Wochen', 'Herbst, nach den ersten Regenfällen',
    1, 'diurnal', 'Samen (Grassamen, Löwenzahn, Chia, Mohn, Leinsamen); zusätzlich Insekten', 'Kaum nötig; gelegentlich Honigwasser oder Obst', 'Samen trocken anbieten; feucht gewordene Samen keimen oder schimmeln.',
    'Tiefe Erdnester mit Samenkammern', 'Ytong, Gips, Erdnest; trockene Kammern für den Samenvorrat', 'L', 'Sand, Sand-Lehm-Gemisch',
    NULL, 'Klassische Einsteigerart, wird groß.',
    pg_temp.antwiki('Messor barbarus')),
(NULL, 'Pheidole pallidula', 'Pheidole', 'Myrmicinae', 'Attini', 'Dickkopfameise',
    'Mittelmeergebiet bis Zentralasien', 'Trockene, warme Standorte, auch Siedlungen',
    '5–6 mm', '2–3 mm (Minor), 3,5–4,5 mm (Major)', '4–5 mm', 'Gelb- bis rotbraun', true,
    20, 30, 22, 26, 40, 60, 50, 70,
    'optional', 'Dezember – Februar (kühlere Ruhephase)', 10, 15,
    'facultative', 'claustral', 'bis mehrere tausend Arbeiterinnen', NULL, 'ca. 5–7 Wochen', 'Juni – August',
    1, 'both', 'Insekten und Samen', 'Honigwasser, Zuckerwasser', NULL,
    'Erdnester unter Steinen und in Mauerritzen', 'Ytong, Gips, Acryl', 'S–M', 'Sand-Lehm-Gemisch',
    NULL, 'Majore mit großem Kopf knacken Samen und Beute. Klein – guter Ausbruchschutz nötig.',
    pg_temp.antwiki('Pheidole pallidula')),
(NULL, 'Crematogaster scutellaris', 'Crematogaster', 'Myrmicinae', 'Crematogastrini', NULL,
    'Mittelmeergebiet', 'Lichte Wälder, Korkeichen, Olivenhaine',
    '8–10 mm', '3–5 mm', '4–5 mm', 'Kopf rot, Körper schwarz', false,
    20, 28, 22, 26, 40, 60, 50, 70,
    'optional', 'Dezember – Februar (kühlere Ruhephase)', 10, 15,
    'monogyne', 'claustral', 'bis mehrere tausend Arbeiterinnen', NULL, 'ca. 6–8 Wochen', 'Herbst',
    2, 'both', 'Insekten', 'Honigwasser, Zuckerwasser – mag Süßes sehr', NULL,
    'In Holz, Kork und Rinde', 'Kork, Holz, Ytong', 'M', 'Sand-Lehm-Gemisch, Rindenstücke',
    NULL, 'Hebt bei Störung den herzförmigen Hinterleib und sondert Abwehrsekret ab.',
    pg_temp.antwiki('Crematogaster scutellaris')),
(NULL, 'Camponotus barbaricus', 'Camponotus', 'Formicinae', 'Camponotini', NULL,
    'Westliches Mittelmeergebiet, Nordafrika', 'Trockene, warme Offenflächen und lichte Wälder',
    '14–16 mm', '6–14 mm', '8–10 mm', 'Schwarz mit rotbraunen Anteilen, Majore mit großem Kopf', true,
    22, 30, 22, 28, 30, 50, 50, 70,
    'optional', 'Dezember – Februar (kühlere Ruhephase)', 12, 16,
    'monogyne', 'claustral', 'bis mehrere tausend Arbeiterinnen', 'über 10 Jahre', 'ca. 6–8 Wochen', 'Mai – Juni',
    1, 'nocturnal', 'Insekten', 'Honigwasser, Zuckerwasser, Früchte', NULL,
    'Erdnester unter Steinen', 'Ytong, Gips, Acryl', 'M–L', 'Sand, Sand-Lehm-Gemisch',
    NULL, NULL,
    pg_temp.antwiki('Camponotus barbaricus')),
-- Tropen und Subtropen
(NULL, 'Camponotus nicobarensis', 'Camponotus', 'Formicinae', 'Camponotini', NULL,
    'Süd- und Südostasien', 'Warme, trockene bis halbtrockene Lebensräume, auch Siedlungen',
    '15–16 mm', '6–12 mm', '10 mm', 'Rotbraun bis dunkelbraun', true,
    22, 32, 24, 28, 30, 50, 50, 70,
    'none', NULL, NULL, NULL,
    'oligogyne', 'claustral', 'mehrere tausend Arbeiterinnen', 'über 15 Jahre', 'ca. 6–8 Wochen, temperaturabhängig', 'Zu Beginn der Regenzeit',
    1, 'nocturnal', 'Insekten: Fliegen, Heimchen, kleine Grillen, Schaben', 'Honigwasser, Zuckerwasser, Früchte', NULL,
    'In morschem Holz und anderen Hohlräumen', 'Ytong, Gips, Acryl, Kork', 'M–L', 'Sand, Sand-Lehm-Gemisch',
    NULL, 'Tropische Einsteigerart. Tagsüber viel Aktivität kann Futtermangel bedeuten.',
    pg_temp.antwiki('Camponotus nicobarensis')),
(NULL, 'Polyrhachis dives', 'Polyrhachis', 'Formicinae', 'Camponotini', NULL,
    'Süd- und Südostasien, Nordaustralien', 'Wälder und Gebüsch, Nester aus Larvenseide in der Vegetation',
    '8–9 mm', '5–6 mm', '5–6 mm', 'Schwarz mit goldenen Härchen am Hinterleib', false,
    24, 30, 25, 28, 50, 70, 60, 80,
    'none', NULL, NULL, NULL,
    'polygyne', 'claustral', 'bis mehrere 10.000 Arbeiterinnen', NULL, NULL, 'Regenzeit',
    2, 'diurnal', 'Insekten', 'Honigwasser, Zuckerwasser', NULL,
    'Seidennester in Pflanzen oder in Hohlräumen', 'Acryl, Ytong; Pflanzen und Zweige in der Arena', 'M–L', 'Erde, Pflanzen',
    NULL, 'Webt mit Larvenseide – Zweige und Pflanzen in der Arena anbieten.',
    pg_temp.antwiki('Polyrhachis dives')),
(NULL, 'Oecophylla smaragdina', 'Oecophylla', 'Formicinae', 'Oecophyllini', 'Asiatische Weberameise',
    'Süd- und Südostasien, Nordaustralien', 'Baumkronen tropischer Wälder und Plantagen',
    '15–20 mm', '5–10 mm', '6–8 mm', 'Orange bis rötlich; Königin grün', true,
    25, 30, 26, 30, 60, 80, 70, 90,
    'none', NULL, NULL, NULL,
    'monogyne', 'claustral', 'bis mehrere 100.000 Arbeiterinnen', NULL, NULL, 'Regenzeit',
    3, 'diurnal', 'Viele Insekten – sehr hoher Proteinbedarf', 'Honigwasser, Zuckerwasser', NULL,
    'Blattnester in Bäumen, mit Larvenseide verwoben', 'Großes Terrarium mit lebenden Pflanzen', 'XL', 'Erde, lebende Pflanzen',
    NULL, 'Nur für Erfahrene: braucht viel Platz, Pflanzen, hohe Luftfeuchte und sehr viel Futter.',
    pg_temp.antwiki('Oecophylla smaragdina')),
(NULL, 'Atta cephalotes', 'Atta', 'Myrmicinae', 'Attini', 'Blattschneiderameise',
    'Mittel- und Südamerika', 'Tropische Wälder',
    '20–25 mm', '1,5–15 mm', '20 mm', 'Rotbraun', true,
    24, 28, 24, 27, 60, 80, 80, 95,
    'none', NULL, NULL, NULL,
    'monogyne', 'claustral', 'bis mehrere Millionen Arbeiterinnen', 'über 10 Jahre', NULL, 'Regenzeit',
    3, 'both', 'Frische Blätter (Brombeere, Rose, Liguster, Eiche) als Pilzsubstrat', 'Früchte, etwas Honigwasser', 'Ernährt sich vom selbst gezüchteten Pilz, nicht direkt von den Blättern.',
    'Unterirdische Pilzkammern', 'Spezielle Pilzkammern (Glas/Acryl) mit Abfallbehälter', 'XL', 'Keines in der Arena; Pilzkammern feucht halten',
    NULL, 'Nur für Erfahrene: täglich frische Blätter, stabile Luftfeuchte, Pilz ist empfindlich.',
    pg_temp.antwiki('Atta cephalotes')),
(NULL, 'Myrmecocystus mexicanus', 'Myrmecocystus', 'Formicinae', 'Lasiini', 'Honigtopfameise',
    'Südwesten der USA, Mexiko', 'Wüsten und Halbwüsten',
    '10–12 mm', '4–7 mm', '5–6 mm', 'Gelbbraun; Speicherameisen (Repleten) mit prallem, hellem Hinterleib', true,
    22, 32, 24, 28, 20, 40, 40, 60,
    'optional', 'Dezember – Februar (kühlere Ruhephase)', 12, 18,
    'facultative', 'claustral', 'bis wenige tausend Arbeiterinnen', 'über 10 Jahre', 'ca. 6–8 Wochen', 'Nach Sommerregen',
    2, 'nocturnal', 'Insekten', 'Honigwasser, Zuckerwasser – wird in Repleten gespeichert', NULL,
    'Tiefe Erdnester mit Speicherkammern', 'Ytong, Gips, Erdnest', 'M', 'Sand, Sand-Lehm-Gemisch',
    NULL, 'Braucht hohe, trockene Arena und warme Nestbereiche.',
    pg_temp.antwiki('Myrmecocystus mexicanus')),
(NULL, 'Harpegnathos venator', 'Harpegnathos', 'Ponerinae', 'Ponerini', NULL,
    'Süd- und Südostasien', 'Feuchte Wälder, Bodenstreu',
    '15–18 mm', '13–16 mm', '12–15 mm', 'Dunkelbraun mit hellen Mandibeln', false,
    24, 28, 24, 28, 60, 80, 70, 90,
    'none', NULL, NULL, NULL,
    'monogyne', 'semi_claustral', 'meist unter 100 Arbeiterinnen', NULL, 'ca. 6–8 Wochen', 'Regenzeit',
    2, 'diurnal', 'Lebende oder frisch getötete Insekten (Heimchen, Grillen, Schaben)', 'Kaum; gelegentlich Honigwasser', 'Jagt aktiv mit Sprüngen – lebendes Futter wird bevorzugt.',
    'Erdnester in feuchtem Boden', 'Ytong, Gips; feucht halten', 'S–M', 'Erde, Laub',
    NULL, 'Arbeiterinnen können nach dem Tod der Königin zu Gamergates werden und die Kolonie weiterführen.',
    pg_temp.antwiki('Harpegnathos venator'));
