-- Artenkatalog erweitert:
--  * translations: Steckbrief-Texte in weiteren Sprachen ({"en": {"distribution": …}}); die
--    deutschen Spalten bleiben die Quelle, fehlende Übersetzungen fallen auf sie zurück.
--  * eu_invasive: Arten der Unionsliste invasiver gebietsfremder Arten (Verordnung (EU)
--    Nr. 1143/2014) – Haltung verboten; die App warnt im Steckbrief und bei Kolonien.
--    Ameisen seit der Durchführungsverordnung (EU) 2022/1203 (gilt seit 2. August 2022).
--  * user_settings.flight_watch: Arten, deren Schwarmflugzeit die App ankündigen soll.
ALTER TABLE species
    ADD COLUMN translations jsonb   NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(translations) = 'object'),
    ADD COLUMN eu_invasive  boolean NOT NULL DEFAULT false;

ALTER TABLE user_settings
    ADD COLUMN flight_watch jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(flight_watch) = 'array');

-- Invasive Ameisen der Unionsliste (Katalog, damit Steckbrief und Warnung erscheinen)
INSERT INTO species (owner_id, scientific_name, genus, subfamily, tribe, german_name, distribution,
    hibernation, legal_note, notes, eu_invasive, sources) VALUES
    (NULL, 'Solenopsis invicta', 'Solenopsis', 'Myrmicinae', 'Solenopsidini', 'Rote Feuerameise', 'Südamerika; eingeschleppt u. a. in die USA, nach China und Australien',
     'none', 'EU: invasive gebietsfremde Art von unionsweiter Bedeutung (Durchführungsverordnung (EU) 2022/1203, gilt seit 2. August 2022). Halten, Züchten, Kaufen, Verkaufen, Transportieren und Freisetzen sind in der EU verboten (Verordnung (EU) Nr. 1143/2014, Art. 7).',
     'Nicht halten. Verdachtsfälle in der Natur den zuständigen Naturschutzbehörden melden.', true, '[{"title": "Durchführungsverordnung (EU) 2022/1203 – Unionsliste invasiver Arten", "url": "https://eur-lex.europa.eu/eli/reg_impl/2022/1203/oj"}, {"title": "Verordnung (EU) Nr. 1143/2014 über invasive gebietsfremde Arten", "url": "https://eur-lex.europa.eu/eli/reg/2014/1143/oj"}, {"title": "AntWiki", "url": "https://www.antwiki.org/wiki/Solenopsis_invicta"}]'::jsonb),
    (NULL, 'Solenopsis richteri', 'Solenopsis', 'Myrmicinae', 'Solenopsidini', 'Schwarze Feuerameise', 'Südamerika; eingeschleppt in die USA',
     'none', 'EU: invasive gebietsfremde Art von unionsweiter Bedeutung (Durchführungsverordnung (EU) 2022/1203, gilt seit 2. August 2022). Halten, Züchten, Kaufen, Verkaufen, Transportieren und Freisetzen sind in der EU verboten (Verordnung (EU) Nr. 1143/2014, Art. 7).',
     'Nicht halten. Verdachtsfälle in der Natur den zuständigen Naturschutzbehörden melden.', true, '[{"title": "Durchführungsverordnung (EU) 2022/1203 – Unionsliste invasiver Arten", "url": "https://eur-lex.europa.eu/eli/reg_impl/2022/1203/oj"}, {"title": "Verordnung (EU) Nr. 1143/2014 über invasive gebietsfremde Arten", "url": "https://eur-lex.europa.eu/eli/reg/2014/1143/oj"}, {"title": "AntWiki", "url": "https://www.antwiki.org/wiki/Solenopsis_richteri"}]'::jsonb),
    (NULL, 'Solenopsis geminata', 'Solenopsis', 'Myrmicinae', 'Solenopsidini', 'Tropische Feuerameise', 'Amerika; in viele tropische Regionen verschleppt',
     'none', 'EU: invasive gebietsfremde Art von unionsweiter Bedeutung (Durchführungsverordnung (EU) 2022/1203, gilt seit 2. August 2022). Halten, Züchten, Kaufen, Verkaufen, Transportieren und Freisetzen sind in der EU verboten (Verordnung (EU) Nr. 1143/2014, Art. 7).',
     'Nicht halten. Verdachtsfälle in der Natur den zuständigen Naturschutzbehörden melden.', true, '[{"title": "Durchführungsverordnung (EU) 2022/1203 – Unionsliste invasiver Arten", "url": "https://eur-lex.europa.eu/eli/reg_impl/2022/1203/oj"}, {"title": "Verordnung (EU) Nr. 1143/2014 über invasive gebietsfremde Arten", "url": "https://eur-lex.europa.eu/eli/reg/2014/1143/oj"}, {"title": "AntWiki", "url": "https://www.antwiki.org/wiki/Solenopsis_geminata"}]'::jsonb),
    (NULL, 'Wasmannia auropunctata', 'Wasmannia', 'Myrmicinae', 'Attini', 'Kleine Feuerameise', 'Mittel- und Südamerika; in viele tropische Regionen verschleppt',
     'none', 'EU: invasive gebietsfremde Art von unionsweiter Bedeutung (Durchführungsverordnung (EU) 2022/1203, gilt seit 2. August 2022). Halten, Züchten, Kaufen, Verkaufen, Transportieren und Freisetzen sind in der EU verboten (Verordnung (EU) Nr. 1143/2014, Art. 7).',
     'Nicht halten. Verdachtsfälle in der Natur den zuständigen Naturschutzbehörden melden.', true, '[{"title": "Durchführungsverordnung (EU) 2022/1203 – Unionsliste invasiver Arten", "url": "https://eur-lex.europa.eu/eli/reg_impl/2022/1203/oj"}, {"title": "Verordnung (EU) Nr. 1143/2014 über invasive gebietsfremde Arten", "url": "https://eur-lex.europa.eu/eli/reg/2014/1143/oj"}, {"title": "AntWiki", "url": "https://www.antwiki.org/wiki/Wasmannia_auropunctata"}]'::jsonb)
ON CONFLICT DO NOTHING;

-- Englische Steckbriefe der Katalog-Arten
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Leafcutter ant", "distribution": "Central and South America", "habitat": "Tropical forests", "worker_size": "1.5–15 mm", "coloration": "Reddish brown", "colony_size": "up to several million workers", "queen_lifespan": "over 10 years", "nuptial_flight": "Rainy season", "diet_protein": "Fresh leaves (bramble, rose, privet, oak) as fungus substrate", "diet_carbohydrate": "Fruit, a little honey water", "diet_notes": "Feeds on the fungus it grows itself, not directly on the leaves.", "nesting": "Underground fungus chambers", "formicarium": "Special fungus chambers (glass/acrylic) with a waste container", "substrate": "None in the outworld; keep the fungus chambers moist", "notes": "For experienced keepers only: fresh leaves every day, stable humidity, the fungus is sensitive."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Atta cephalotes';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Barbary carpenter ant", "distribution": "Western Mediterranean, North Africa", "habitat": "Dry, warm open land and open woodland", "coloration": "Black with reddish-brown parts, majors with a large head", "hibernation_period": "December – February (cooler rest period)", "colony_size": "up to several thousand workers", "queen_lifespan": "over 10 years", "development": "approx. 6–8 weeks", "nuptial_flight": "May – June", "diet_protein": "Insects", "diet_carbohydrate": "Honey water, sugar water, fruit", "nesting": "Soil nests under stones", "formicarium": "Ytong, plaster, acrylic", "substrate": "Sand, sand-loam mix"}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Camponotus barbaricus';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Hercules ant", "distribution": "Northern and Central Europe, northern Asia, North America", "habitat": "Coniferous forests, in mountains up to the tree line", "coloration": "Black with a reddish-brown mesosoma", "hibernation_period": "October – April", "colony_size": "up to several thousand workers", "queen_lifespan": "over 20 years", "development": "approx. 8–10 weeks", "nuptial_flight": "May – July", "diet_protein": "Insects", "diet_carbohydrate": "Honey water, sugar water", "nesting": "In trunks and stumps of conifers", "formicarium": "Wood, Ytong, plaster", "substrate": "Sand-loam mix, pieces of bark", "notes": "Needs a long, cool hibernation."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Camponotus herculeanus';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Brown-black carpenter ant", "distribution": "Central and Southern Europe to Western Asia", "habitat": "Open, warm woodland, forest edges", "coloration": "Black with a reddish-brown mesosoma and gaster base", "hibernation_period": "October – March", "colony_size": "up to a few thousand workers", "queen_lifespan": "over 20 years", "development": "approx. 8 weeks; slow development in the first year", "nuptial_flight": "May – June", "diet_protein": "Insects: house crickets, crickets, cockroaches, flies", "diet_carbohydrate": "Honey water, sugar water, sweet fruit", "nesting": "In rotten wood and in the ground under stones", "formicarium": "Ytong, plaster, wood, acrylic", "substrate": "Sand-loam mix", "notes": "The first hibernation is important; afterwards the colony grows much faster."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Camponotus ligniperda';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Nicobar carpenter ant", "distribution": "South and Southeast Asia", "habitat": "Warm, dry to semi-dry habitats, also settlements", "coloration": "Reddish brown to dark brown", "colony_size": "several thousand workers", "queen_lifespan": "over 15 years", "development": "approx. 6–8 weeks, depending on temperature", "nuptial_flight": "At the start of the rainy season", "diet_protein": "Insects: flies, house crickets, small crickets, cockroaches", "diet_carbohydrate": "Honey water, sugar water, fruit", "nesting": "In rotten wood and other cavities", "formicarium": "Ytong, plaster, acrylic, cork", "substrate": "Sand, sand-loam mix", "notes": "Tropical beginner species. Lots of activity during the day can mean a lack of food."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Camponotus nicobarensis';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Mediterranean acrobat ant", "distribution": "Mediterranean region", "habitat": "Open woodland, cork oaks, olive groves", "coloration": "Head red, body black", "hibernation_period": "December – February (cooler rest period)", "colony_size": "up to several thousand workers", "development": "approx. 6–8 weeks", "nuptial_flight": "Autumn", "diet_protein": "Insects", "diet_carbohydrate": "Honey water, sugar water – loves sweets", "nesting": "In wood, cork and bark", "formicarium": "Cork, wood, Ytong", "substrate": "Sand-loam mix, pieces of bark", "notes": "When disturbed it raises its heart-shaped gaster and releases a defensive secretion."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Crematogaster scutellaris';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Silky ant", "distribution": "Europe, temperate Asia", "habitat": "Forest edges, clearings, gardens", "worker_size": "4.5–7 mm", "coloration": "Greyish black, silky sheen", "hibernation_period": "October – March", "colony_size": "a few hundred to 2,000 workers", "queen_lifespan": "up to approx. 20 years", "development": "approx. 6–8 weeks", "nuptial_flight": "June – August", "diet_protein": "Insects, fairly high protein need while raising brood", "diet_carbohydrate": "Honey water, sugar water, fruit", "nesting": "Soil nests, under stones, in tree stumps", "formicarium": "Ytong, plaster, acrylic, soil nest", "substrate": "Sand-loam mix", "legal_note": "Not to be confused with the protected mound-building wood ants (Formica rufa group).", "notes": "Fast, shy species – escape protection is important."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Formica fusca';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Red-barbed ant", "distribution": "Europe, Central Asia", "habitat": "Dry, warm open land, poor grassland", "worker_size": "4.5–7 mm", "coloration": "Head and gaster black, mesosoma reddish", "hibernation_period": "October – March", "colony_size": "a few hundred to a few thousand workers", "queen_lifespan": "over 10 years", "development": "approx. 6–8 weeks", "nuptial_flight": "June – July", "diet_protein": "Insects", "diet_carbohydrate": "Honey water, sugar water, fruit", "nesting": "Soil nests in dry, sunny ground", "formicarium": "Ytong, plaster, acrylic, soil nest", "substrate": "Sand, sand-loam mix", "legal_note": "Not to be confused with the protected mound-building wood ants (Formica rufa group).", "notes": "Loves warmth, very quick – escape protection is important."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Formica rufibarbis';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Blood-red ant", "distribution": "Europe, temperate Asia", "habitat": "Forest edges, heaths, clearings", "coloration": "Head and mesosoma red, gaster black", "hibernation_period": "October – March", "colony_size": "several thousand workers", "queen_lifespan": "over 10 years", "development": "approx. 6–8 weeks", "nuptial_flight": "July – August", "diet_protein": "Insects, pupae of Serviformica (raids)", "diet_carbohydrate": "Honey water, sugar water", "nesting": "Soil nests, often with host ants (Formica fusca, F. rufibarbis)", "formicarium": "Soil nest, Ytong", "substrate": "Sand-loam mix", "notes": "Social parasite: the queen founds only with pupae or workers of a host species. For advanced keepers."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Formica sanguinea';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Jumping ant", "distribution": "South and Southeast Asia", "habitat": "Humid forests, leaf litter", "coloration": "Dark brown with pale mandibles", "colony_size": "usually under 100 workers", "development": "approx. 6–8 weeks", "nuptial_flight": "Rainy season", "diet_protein": "Live or freshly killed insects (house crickets, crickets, cockroaches)", "diet_carbohydrate": "Hardly any; occasionally honey water", "diet_notes": "Hunts actively with jumps – live food is preferred.", "nesting": "Soil nests in moist ground", "formicarium": "Ytong, plaster; keep moist", "substrate": "Soil, leaves", "notes": "After the queen dies, workers can become gamergates and carry on the colony."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Harpegnathos venator';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Yellow meadow ant", "distribution": "Europe, Asia, North Africa", "habitat": "Meadows and pastures, builds soil mounds", "worker_size": "2–4.5 mm", "coloration": "Yellow to yellowish brown; queen brown", "hibernation_period": "October – March", "colony_size": "up to several 10,000 workers", "queen_lifespan": "over 15 years", "development": "slow, often 2–3 months", "nuptial_flight": "July – August", "diet_protein": "Small insects, cut up", "diet_carbohydrate": "Honey water; in nature lives almost entirely on honeydew of underground root aphids", "nesting": "Purely underground, hardly comes to the surface", "formicarium": "Soil nest, Ytong with soil, moist plaster nest", "substrate": "Soil, sand-loam mix", "notes": "Grows slowly and is rarely seen – rather for patient keepers."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Lasius flavus';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Black garden ant", "distribution": "Europe, Western and Central Asia", "habitat": "Open land, gardens, roadsides, settlements", "male_size": "3.5–4.5 mm", "coloration": "Blackish brown to greyish black", "hibernation_period": "October – March", "colony_size": "up to over 10,000 workers", "queen_lifespan": "up to approx. 29 years (record in captivity)", "development": "approx. 6–8 weeks from egg to worker", "nuptial_flight": "June – August", "diet_protein": "Small insects: fruit flies, house crickets, crickets, cockroaches (pieces)", "diet_carbohydrate": "Honey water, sugar water; in nature mainly honeydew from aphids", "nesting": "Soil nests, often under stones; also in rotten wood", "formicarium": "Ytong, plaster, acrylic, soil nest", "substrate": "Sand-loam mix", "notes": "Robust beginner species. Founding queens need no food until the first workers."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Lasius niger';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Mountain red ant", "distribution": "Mountains of Southern and Central Europe, including the Alps", "habitat": "Sunny, stony slopes and gravel areas in the uplands", "worker_size": "5–7.5 mm", "coloration": "Reddish brown", "hibernation_period": "October – April", "colony_size": "a few hundred to a few thousand workers", "queen_lifespan": "over 10 years", "development": "approx. 6–8 weeks", "nuptial_flight": "June – August", "diet_protein": "Insects", "diet_carbohydrate": "Honey water, sugar water", "diet_notes": "Founding queens need food.", "nesting": "Soil nests under stones", "formicarium": "Ytong, plaster", "substrate": "Sand-loam mix, gravel", "notes": "Stings painfully. Needs a long hibernation."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Manica rubida';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Harvester ant", "distribution": "Western Mediterranean: Iberian Peninsula, southern France, Italy, North Africa", "habitat": "Dry, open areas, fields", "coloration": "Black; large workers with a red head", "hibernation_period": "November – February (cooler rest period)", "colony_size": "up to several 10,000 workers", "queen_lifespan": "over 10 years", "development": "approx. 6–8 weeks", "nuptial_flight": "Autumn, after the first rains", "diet_protein": "Seeds (grass seeds, dandelion, chia, poppy, linseed); insects as well", "diet_carbohydrate": "Hardly needed; occasionally honey water or fruit", "diet_notes": "Offer seeds dry; seeds that got moist germinate or go mouldy.", "nesting": "Deep soil nests with seed chambers", "formicarium": "Ytong, plaster, soil nest; dry chambers for the seed store", "substrate": "Sand, sand-loam mix", "notes": "Classic beginner species, grows large."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Messor barbarus';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Harvester ant", "distribution": "Southern and Central Europe (in Austria mainly in the east), to Central Asia", "habitat": "Dry, warm open land, dry grassland", "worker_size": "3.5–10 mm", "coloration": "Dark brown to black", "hibernation_period": "November – March", "colony_size": "several thousand workers", "queen_lifespan": "over 10 years", "development": "approx. 6–8 weeks", "nuptial_flight": "May – July", "diet_protein": "Seeds (grass seeds, dandelion, chia, poppy); insects as well", "diet_carbohydrate": "Hardly needed; occasionally honey water", "diet_notes": "Offer seeds dry; the colony clears out mouldy chambers itself.", "nesting": "Deep soil nests with seed chambers", "formicarium": "Ytong, plaster, soil nest; dry chambers for the seed store", "substrate": "Sand, sand-loam mix", "notes": "Seed harvester – ideal for beginners with little time."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Messor structor';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Honeypot ant", "distribution": "Southwestern USA, Mexico", "habitat": "Deserts and semi-deserts", "coloration": "Yellowish brown; repletes with a swollen, pale gaster", "hibernation_period": "December – February (cooler rest period)", "colony_size": "up to a few thousand workers", "queen_lifespan": "over 10 years", "development": "approx. 6–8 weeks", "nuptial_flight": "After summer rains", "diet_protein": "Insects", "diet_carbohydrate": "Honey water, sugar water – stored in repletes", "nesting": "Deep soil nests with storage chambers", "formicarium": "Ytong, plaster, soil nest", "substrate": "Sand, sand-loam mix", "notes": "Needs a tall, dry outworld and warm nest areas."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Myrmecocystus mexicanus';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "European fire ant", "distribution": "Europe, temperate Asia; introduced to North America", "habitat": "Moist meadows, gardens, forest edges", "queen_size": "5.5–7 mm", "worker_size": "4–5.5 mm", "coloration": "Reddish brown to yellowish red", "hibernation_period": "October – March", "colony_size": "a few hundred to a few thousand workers", "queen_lifespan": "over 10 years", "development": "approx. 6–8 weeks", "nuptial_flight": "August – September", "diet_protein": "Insects", "diet_carbohydrate": "Honey water, sugar water", "diet_notes": "Founding queens forage and need food.", "nesting": "Soil nests, under stones, in moss and dead wood", "formicarium": "Ytong, plaster, acrylic", "substrate": "Soil, sand-loam mix", "notes": "Likes it moist. Stings noticeably."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Myrmica rubra';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Asian weaver ant", "distribution": "South and Southeast Asia, northern Australia", "habitat": "Tree canopies of tropical forests and plantations", "coloration": "Orange to reddish; queen green", "colony_size": "up to several 100,000 workers", "nuptial_flight": "Rainy season", "diet_protein": "Many insects – very high protein need", "diet_carbohydrate": "Honey water, sugar water", "nesting": "Leaf nests in trees, woven with larval silk", "formicarium": "Large terrarium with living plants", "substrate": "Soil, living plants", "notes": "For experienced keepers only: needs a lot of space, plants, high humidity and a lot of food."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Oecophylla smaragdina';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Big-headed ant", "distribution": "Mediterranean region to Central Asia", "habitat": "Dry, warm places, also settlements", "worker_size": "2–3 mm (minor), 3.5–4.5 mm (major)", "coloration": "Yellowish to reddish brown", "hibernation_period": "December – February (cooler rest period)", "colony_size": "up to several thousand workers", "development": "approx. 5–7 weeks", "nuptial_flight": "June – August", "diet_protein": "Insects and seeds", "diet_carbohydrate": "Honey water, sugar water", "nesting": "Soil nests under stones and in wall crevices", "formicarium": "Ytong, plaster, acrylic", "substrate": "Sand-loam mix", "notes": "Majors with large heads crack seeds and prey. Small – good escape protection needed."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Pheidole pallidula';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Golden-haired weaver ant", "distribution": "South and Southeast Asia, northern Australia", "habitat": "Forests and shrubs, nests of larval silk in the vegetation", "coloration": "Black with golden hairs on the gaster", "colony_size": "up to several 10,000 workers", "nuptial_flight": "Rainy season", "diet_protein": "Insects", "diet_carbohydrate": "Honey water, sugar water", "nesting": "Silk nests in plants or in cavities", "formicarium": "Acrylic, Ytong; plants and twigs in the outworld", "substrate": "Soil, plants", "notes": "Weaves with larval silk – offer twigs and plants in the outworld."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Polyrhachis dives';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Tropical fire ant", "distribution": "The Americas; spread to many tropical regions", "legal_note": "EU: invasive alien species of Union concern (Implementing Regulation (EU) 2022/1203, in force since 2 August 2022). Keeping, breeding, buying, selling, transporting and releasing are prohibited in the EU (Regulation (EU) No 1143/2014, Art. 7).", "notes": "Do not keep. Report suspected finds in the wild to the responsible nature conservation authorities."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Solenopsis geminata';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Red imported fire ant", "distribution": "South America; introduced to the USA, China and Australia, among others", "legal_note": "EU: invasive alien species of Union concern (Implementing Regulation (EU) 2022/1203, in force since 2 August 2022). Keeping, breeding, buying, selling, transporting and releasing are prohibited in the EU (Regulation (EU) No 1143/2014, Art. 7).", "notes": "Do not keep. Report suspected finds in the wild to the responsible nature conservation authorities."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Solenopsis invicta';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Black imported fire ant", "distribution": "South America; introduced to the USA", "legal_note": "EU: invasive alien species of Union concern (Implementing Regulation (EU) 2022/1203, in force since 2 August 2022). Keeping, breeding, buying, selling, transporting and releasing are prohibited in the EU (Regulation (EU) No 1143/2014, Art. 7).", "notes": "Do not keep. Report suspected finds in the wild to the responsible nature conservation authorities."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Solenopsis richteri';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Acorn ant", "distribution": "Western and Central Europe", "habitat": "Deciduous forests, in acorns, nutshells and twigs", "queen_size": "3.5–4 mm", "coloration": "Yellowish brown, gaster with a dark band", "hibernation_period": "October – March", "colony_size": "usually under 200 workers", "queen_lifespan": "over 10 years", "development": "approx. 6–8 weeks", "nuptial_flight": "July – August", "diet_protein": "Small insects (fruit flies, cut-up house crickets)", "diet_carbohydrate": "Honey water, sugar water", "diet_notes": "Feed only small amounts, remove leftovers quickly.", "nesting": "In cavities of acorns, nuts and thin twigs", "formicarium": "Test tube, small acrylic or plaster nests", "substrate": "Forest soil, leaves", "notes": "Tiny species that needs very little space."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Temnothorax nylanderi';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Pavement ant", "distribution": "Europe, temperate Asia; introduced to North America", "habitat": "Open, sunny areas, roadsides, lawns", "worker_size": "2.5–4 mm", "coloration": "Dark brown to black", "hibernation_period": "October – March", "colony_size": "up to several 10,000 workers", "queen_lifespan": "over 10 years", "development": "approx. 6–8 weeks", "nuptial_flight": "June – July", "diet_protein": "Insects, also seeds", "diet_carbohydrate": "Honey water, sugar water", "nesting": "Soil nests under stones and in paving cracks", "formicarium": "Ytong, plaster, acrylic", "substrate": "Sand-loam mix", "notes": "Actually a species complex, hardly distinguishable in the field. Active, can sting, but weakly."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Tetramorium caespitum';
UPDATE species SET translations = jsonb_build_object('en', '{"german_name": "Electric ant (little fire ant)", "distribution": "Central and South America; spread to many tropical regions", "legal_note": "EU: invasive alien species of Union concern (Implementing Regulation (EU) 2022/1203, in force since 2 August 2022). Keeping, breeding, buying, selling, transporting and releasing are prohibited in the EU (Regulation (EU) No 1143/2014, Art. 7).", "notes": "Do not keep. Report suspected finds in the wild to the responsible nature conservation authorities."}'::jsonb)
    WHERE owner_id IS NULL AND scientific_name = 'Wasmannia auropunctata';
