#!/usr/bin/env python3
"""Regenerates lib/l10n/<lang>.dart from tool/l10n/<lang>.json (German → translation).
Reports tr() keys without a translation and placeholder mismatches. Run from app/.
Usage: tool/i18n_gen.py en"""
import json, re, sys
sys.path.insert(0, "tool")
from i18n_keys import keys

lang = sys.argv[1]
table = json.load(open(f"tool/l10n/{lang}.json", encoding="utf-8"))
dynamic = table.pop("_dynamic", {})
missing = [k for k in keys() if k not in table]
bad = [k for k, v in table.items() if sorted(re.findall(r"\{\d\}", k)) != sorted(re.findall(r"\{\d\}", v))]
for k in missing: print("MISSING:", k)
for k in bad: print("PLACEHOLDERS:", k)
if missing or bad: sys.exit(1)
used = set(keys()) | set(dynamic)
def dart(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$").replace("\n", "\\n") + "'"
lines = [f"/// {lang} – see lib/app/i18n.dart. Keys are the German source texts.",
         f"/// Generated by tool/i18n_gen.py from tool/l10n/{lang}.json – edit that file.",
         "const table = <String, String>{"]
for k in sorted(used):
    v = table.get(k, dynamic.get(k))
    lines.append(f"  {dart(k)}: {dart(v)},")
lines.append("};")
open(f"lib/l10n/{lang}.dart", "w", encoding="utf-8").write("\n".join(lines) + "\n")
print(lang, len(used), "entries;", len(set(table) - used), "unused in the json")
